---
apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: eda-st-srlinux-24.10.1
  namespace: clab-eda-st
spec:
  port: 57410
  annotate: true
  operatingSystem: srl
  version: 24.10.1
  versionPath: .system.information.version
  versionMatch: v24\.10\.1.*
  yang: https://eda-asvr.eda-system.svc/eda-system/clab-schemaprofiles/clab-srlinux-24.10.1/srlinux-24.10.1.zip
  nodeUser: admin
  onboardingPassword: NokiaSrl1!
  onboardingUsername: admin
  images:
  - image: fake.bin
    imageMd5: fake.bin.md5