apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: prom-exporter
  namespace: eda-system
spec:
  input:
    app: prom-exporter
    catalog: eda-catalog-builtin-apps
    operation: install
    vendor: nokia
    version:
      type: semver
      value: v2.0.0
  type: app-installer
---
apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: kafka-exporter
  namespace: eda-system
spec:
  input:
    app: kafka-exporter
    catalog: eda-catalog-builtin-apps
    operation: install
    vendor: nokia
    version:
      type: semver
      value: v2.0.1
  type: app-installer